name: First Workflow
on: workflow_dispatch
jobs: 
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: echo "Message from the first job, first step"
      - name: Print Goodbye
        run: echo "Done Bye"
        
